version: '3'

services:
  api:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    container_name: go-backend-api
    depends_on: ["postgres", "redis"]
    user: "${USER_UID}:${USER_GID}"
    networks: ["net"]
    # network_mode: bridge
    ports: ["127.0.0.1:${HTTP_Port}:${HTTP_Port}", "9015:9015", "9019:9019"]
    environment: ["TZ=Asia/Shanghai"]
    working_dir: /app
    volumes:
    - ./configs/:/app/configs:ro
    - ./logs/:/app/logs
    - ./site/:/app/site
    # - ./data/${APP_Name}:/app/data
    command:
    - ./target/go-backend
    - api
    - -release
    - -config=configs/prod.yaml
    - -http.addr=:${HTTP_Port}

  crons:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    container_name: go-backend-crons
    depends_on: ["postgres", "redis"]
    user: "${USER_UID}:${USER_GID}"
    networks: ["net"]
    # network_mode: bridge
    environment: ["TZ=Asia/Shanghai"]
    working_dir: /app
    volumes:
    - ./configs/:/app/configs:ro
    - ./logs/:/app/logs
    command:
    - ./target/go-backend
    - crons
    - -config=configs/crons.yaml

  swagger:
    image: ${IMAGE_Name}:${IMAGE_Tag}
    restart: always
    container_name: go-backend-swagger
    user: "${USER_UID}:${USER_GID}"
    network_mode: bridge
    ports: ["9018:9018"]
    environment: ["TZ=Asia/Shanghai"]
    volumes:
    - ./configs/swagger.yaml:/app/configs/swagger.yaml:ro
    command:
    - ./target/main
    - swagger
    - -config=configs/swagger.yaml
    - -http.addr=:9017

  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: go-backend-postgres
    networks: ["net"]
    # ports: ["127.0.0.1:5432:5432"]
    environment:
    - TZ=Asia/Shanghai
    - PGTZ=Asia/Shanghai
    - POSTGRES_USER=account
    - POSTGRES_DB=db
    - POSTGRES_PASSWORD=password
    - PGDATA=/var/lib/postgresql/data
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    user: "${USER_UID}:${USER_GID}"
    networks: ["net"]
    # ports: ['127.0.0.1:6379:6379']
    container_name: go-backend-redis
    deploy:
      resources:
        limits:
          memory: 2.0G # 512M
    environment:
    - TZ=Asia/Shanghai
    # ALLOW_EMPTY_PASSWORD is recommended only for development.
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    working_dir: /app
    volumes:
    - ./configs/redis.conf:/app/configs/redis.conf
    - ./data/redis:/app/data
    command:
    - redis-server
    - /app/configs/redis.conf
    - --loglevel
    - warning
    - --save
    - 30
    - 10

networks:
  net: { name: "go-backend", driver: bridge, external: false }
