---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: go-backend
spec:
  type: ClusterIP
  # clusterIP: 10.107.98.176
  selector: { app: go-backend }
  ports:
  - { name: http, protocol: TCP, port: 9010, targetPort: 9010 }
  - { name: rpc, protocol: TCP, port: 9020, targetPort: 9020 }

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: prod
  name: go-backend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/limit-connections: "1024"
    nginx.ingress.kubernetes.io/limit-rps: "256"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts: [ "go-backend.k8s.domain" ]
    secretName: k8s.domain

  rules:
  - host: go-backend.k8s.domain
    http:
      paths:
      - pathType: Prefix
        path: /api/
        backend:
          service: { name: htto, port: { number: 9010 } }
      - pathType: ImplementationSpecific
        path: /
        backend:
          service: { name: grpc, port: { number: 9020 } }
