app_name: go-backend
app_version: 1.0.0
image_name: registry.cn-shanghai.aliyuncs.com/d2jvkpn/go-backend
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]
repository: git@github.com:d2jvkpn/go-backend.git

api_config: |
  ##### location: configs/local.yaml

  http:
    path: ""
    allow_origins: ["*"]
    tls: false
    cer: configs/site.cer
    key: configs/site.key

  grpc:
    tls: false
    cer: configs/site.cer
    key: configs/site.key

  jwt:
    key: "abcABC123"
    interval: 30m
    duration: 0
    method: 256

  postgres:
    # dsn: "host=127.0.0.1 port=5432 user=account password=password dbname=database sslmode=disable"
    dsn: postgres://account:password@127.0.0.1:5432/database?sslmode=disable
    max_idle_conns: 4
    max_open_conns: 32
    conn_max_idle_time: 15m
    conn_max_lifetime: 30m

  redis:
    addr: "127.0.0.1:6379"
    username: ""
    password: "password"
    db: 0
    protocol: 3
    min_idle_conns: 4
    max_idle_conns: 8
    max_active_conns: 32

  prometheus:
    enabled: false
    path: /metrics

  opentelemetry:
    tls: false
    address: 127.0.0.1:4317
    trace: false
    metrics: false

crons_config: |
  ##### location: configs/crons.yaml

  postgres:
    # dsn: "host=127.0.0.1 port=5432 user=account password=password dbname=database sslmode=disable"
    dsn: postgres://account:password@127.0.0.1:5432/database?sslmode=disable
    max_idle_conns: 4
    max_open_conns: 32
    conn_max_idle_time: 15m
    conn_max_lifetime: 30m

  redis:
    addr: "127.0.0.1:6379"
    username: ""
    password: "password"
    db: 0
    protocol: 3
    min_idle_conns: 4
    max_idle_conns: 8
    max_active_conns: 32

swagger_config: |
  ##### location: configs/swagger.yaml

  swagger:
    accounts:
    - { name: "account", password: "password" }
