app_name: backend-api
app_version: 1.0.0
authors: ["d2jvkpn <d2jvkpn@noreply.local>"]

repository: git@github.com:d2jvkpn/fullstack-go-vue.git
image_name: local/fullstack-go-vue/backend-api

config: |
  # path: configs/local.yaml

  init:
    firstname: d2jvkpn
    lastname: Doe
    email: d2jvkpn@local.dev
    password: cKEvRvCM6Tme1zQ0
    # level: admin
    # status: activated

  http:
    path: /local
    allow_origins: ["*"]
    tls: false
    cer: configs/site.cer
    key: configs/site.key

  captcha:
    enabled: false
    clear: true
    length: 4
    height: 40
    width: 80
    noise_count: 1
    show_line: 1
    source: ABCDEFGHJKLMNPQRSTUVWXY3456789 # ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
    collect_num: 100
    duration: 3m

  grpc:
    tls: false
    cer: configs/site.cer
    key: configs/site.key

  jwt:
    key: "abcABC123_length_ge_32"
    interval: 30m
    duration: 0
    method: 256

  storage:
    provider: local

  postgres:
    # dsn: "host=127.0.0.1 port=5432 user=account password=password dbname=database sslmode=disable"
    dsn: postgres://account:password@127.0.0.1:5432/database?sslmode=disable
    max_idle_conns: 8
    max_open_conns: 256
    conn_max_idle_time: 15m
    conn_max_lifetime: 30m

  redis:
    addr: "127.0.0.1:6379"
    username: ""
    password: "password"
    db: 0
    protocol: 3
    min_idle_conns: 4
    max_idle_conns: 8
    max_active_conns: 32

  elasticsearch:
    addresses: [http://127.0.0.1:9200]
    username: elastic
    password: elastic
    api_key: xxxxxxxx
    headers: {} # map[string][]string
    ca_cert_file: configs/elastic.ca

  prometheus: # optional
    enabled: false
    path: /metrics

  opentelemetry: # optional
    trace: false
    meter: false
    address: 127.0.0.1:4317
    tls: false
