definitions:
  biz_user.LoginRequest:
    properties:
      email:
        example: john@noreply.local
        type: string
        x-order: "02"
      password:
        type: string
        x-order: "03"
      phone:
        example: ^1[3456789][0-9]{9}$
        type: string
        x-order: "01"
    type: object
  biz_user.LoginResponse:
    properties:
      createdAt:
        description: created time RFC3339
        type: string
        x-order: "02"
      email:
        description: |-
          email address
          minLength: 5
          maxLength: 128
          example: john@noreply.local
        type: string
        x-order: "08"
      expiresAt:
        description: unix 时间戳
        example: 1715008592
        type: integer
        x-order: "23"
      firstname:
        description: |-
          firstname
          minLength: 2
          maxLength: 24
          example: John
        type: string
        x-order: "05"
      id:
        description: account id
        type: string
        x-order: "01"
      labels:
        description: labels
        items:
          type: string
        type: array
        x-order: "10"
      lastname:
        description: |-
          lastname
          minLength: 2
          maxLength: 24
          example: John
        type: string
        x-order: "06"
      level:
        description: |-
          level
          enum: admin,editor,reviewer,user,guest
        type: string
        x-order: "09"
      phone:
        description: |-
          Phone number
          minLength: 6
          maxLength: 20
          example: ^1[3456789][0-9]{9}$
        type: string
        x-order: "07"
      status:
        description: account status
        type: string
        x-order: "04"
      token:
        type: string
        x-order: "22"
      tokenId:
        type: string
        x-order: "21"
      updatedAt:
        description: updated time
        type: string
        x-order: "03"
    type: object
  mod_user.Account:
    properties:
      createdAt:
        description: created time RFC3339
        type: string
        x-order: "02"
      email:
        description: |-
          email address
          minLength: 5
          maxLength: 128
          example: john@noreply.local
        type: string
        x-order: "08"
      firstname:
        description: |-
          firstname
          minLength: 2
          maxLength: 24
          example: John
        type: string
        x-order: "05"
      id:
        description: account id
        type: string
        x-order: "01"
      labels:
        description: labels
        items:
          type: string
        type: array
        x-order: "10"
      lastname:
        description: |-
          lastname
          minLength: 2
          maxLength: 24
          example: John
        type: string
        x-order: "06"
      level:
        description: |-
          level
          enum: admin,editor,reviewer,user,guest
        type: string
        x-order: "09"
      phone:
        description: |-
          Phone number
          minLength: 6
          maxLength: 20
          example: ^1[3456789][0-9]{9}$
        type: string
        x-order: "07"
      status:
        description: account status
        type: string
        x-order: "04"
      updatedAt:
        description: updated time
        type: string
        x-order: "03"
    type: object
  mod_user.ChangePassword:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  structs.ResponseOK:
    properties:
      code:
        description: 'string: OK'
        example: ok
        type: string
        x-order: "02"
      data:
        additionalProperties:
          type: string
        description: 'any: response data'
        example:
          answer: hello
          value: "42"
        type: object
        x-order: "03"
      requestId:
        description: 'string: uuid'
        example: 3cc643bd-7f85-493e-8324-6e491db7b3d8
        type: string
        x-order: "01"
    type: object
  utils.PageResult-mod_user_Account:
    properties:
      items:
        items:
          $ref: '#/definitions/mod_user.Account'
        type: array
      pageIndex:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/account/change_password:
    post:
      consumes:
      - application/json
      description: Change the password of an account
      parameters:
      - description: oldPasword newPassword
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mod_user.ChangePassword'
      responses: {}
      summary: Change Password
      tags:
      - account::change_password
  /api/v1/auth/account/delete_accounts:
    get:
      consumes:
      - application/json
      description: '...'
      parameters:
      - collectionFormat: csv
        description: uuids of accounts
        in: query
        items:
          type: string
        name: accountId
        type: array
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Delete accounts
      tags:
      - account::query
  /api/v1/auth/account/logout:
    post:
      description: '...'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.ResponseOK'
      summary: Account logout
      tags:
      - account::logout
  /api/v1/auth/account/query_accounts:
    get:
      consumes:
      - application/json
      description: '...'
      parameters:
      - description: |-
          minimum: 15
          maximum: 100
          default: 15
        in: query
        maximum: 100
        minimum: 10
        name: pageSize
        type: integer
        x-order: "01"
      - description: 'minimum: 1'
        in: query
        name: pageIndex
        type: integer
        x-order: "02"
      - description: |-
          enum: createdAt,updatedAt,firstname,lastname
          default: createdAt + desc
        enum:
        - createdAt
        - updatedAt
        - firstname
        - lastname
        in: query
        name: sort
        type: string
        x-order: "03"
      - description: |-
          enum: asc,desc
          default: asc
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
        x-order: "04"
      - in: query
        name: keyword
        type: string
        x-order: "10"
      - description: |-
          enum: admin,editor,reviewer,user,guest
          default:
        enum:
        - admin
        - editor
        - reviewer
        - user
        - guest
        in: query
        name: level
        type: string
        x-order: "11"
      - description: |-
          enum: created,activated,blocked
          default: activated
        enum:
        - created
        - activated
        - blocked
        in: query
        name: status
        type: string
        x-order: "12"
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.PageResult-mod_user_Account'
      summary: Query accounts
      tags:
      - account::query
  /api/v1/open/account/login:
    post:
      consumes:
      - application/json
      description: login in with phone/email and password
      parameters:
      - description: login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/biz_user.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/biz_user.LoginResponse'
      summary: Account login
      tags:
      - account::login
swagger: "2.0"
