definitions:
  biz_user.LoginRequest:
    properties:
      email:
        example: john@noreply.local
        type: string
        x-order: "02"
      password:
        type: string
        x-order: "03"
      phone:
        example: ^1[3456789][0-9]{9}$
        type: string
        x-order: "01"
    type: object
  biz_user.LoginResponse:
    properties:
      createdAt:
        description: created time RFC3339
        type: string
        x-order: "02"
      email:
        description: email address
        example: john@noreply.local
        maxLength: 128
        minLength: 5
        type: string
        x-order: "08"
      expiresAt:
        description: unix 时间戳
        example: 1715008592
        type: integer
        x-order: "23"
      firstname:
        description: firstname
        example: John
        maxLength: 24
        minLength: 2
        type: string
        x-order: "05"
      id:
        description: account id
        type: string
        x-order: "01"
      labels:
        description: labels
        items:
          type: string
        type: array
        x-order: "10"
      lastname:
        description: lastname
        example: John
        maxLength: 24
        minLength: 2
        type: string
        x-order: "06"
      level:
        description: level
        type: string
        x-order: "09"
      phone:
        description: Phone number
        example: ^1[3456789][0-9]{9}$
        maxLength: 20
        minLength: 6
        type: string
        x-order: "07"
      status:
        description: account status
        type: string
        x-order: "04"
      token:
        type: string
        x-order: "22"
      tokenId:
        type: string
        x-order: "21"
      updatedAt:
        description: updated time
        type: string
        x-order: "03"
    type: object
info:
  contact: {}
paths:
  /api/v1/open/account/login:
    post:
      consumes:
      - application/json
      description: login in with phone/email and password
      parameters:
      - description: login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/biz_user.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/biz_user.LoginResponse'
      summary: Account login
      tags:
      - account::login
swagger: "2.0"
