FROM golang:1-alpine AS builder

ARG APP_Name
ARG APP_Version
ARG GO_ldflags
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=build

#SHELL ["/bin/bash", "-c"]

WORKDIR /opt

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    go env -w GOPROXY="https://goproxy.cn,direct"; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade

ADD ./main.go ./go.mod ./go.sum ./project.yaml ./
COPY ./internal ./internal
COPY ./migrations ./migrations
COPY ./pkg ./pkg
COPY ./proto ./proto
COPY ./bin ./bin
COPY ./deploy ./deploy


####
RUN mkdir -p target

# in alpine, date doesn't parse %:z
# mkdir -p target && go build -o target/main -ldflags="-w -s ${GO_ldflags}" main.go

# https://docs.docker.com/reference/dockerfile/
RUN --mount=type=bind,source=vendor,target=vendor \
  go mod tidy && go build -ldflags="-w -s ${GO_ldflags}" -o target/main main.go

# note: -trimpath will remove -ldflags
#RUN go build -ldflags="-w -s ${GO_ldflags}" -o target/main main.go
ADD ./target/build.yaml /opt/target/

####
# note: -trimpath will remove -ldflags
RUN cd bin/swagger-go && \
  go build -ldflags="-w -s ${GO_ldflags}" -o ../../target/swagger main.go

####
FROM alpine:3

ARG APP_Name
ARG APP_Version
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>
LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=running
#SHELL ["/bin/bash", "-c"]

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata
  # curl gcompat

RUN mkdir -p /opt/target /opt/data /opt/logs
WORKDIR /opt

COPY --from=builder /opt/target/ /opt/target/
# COPY ./migrations ./migrations

VOLUME ["/opt/configs", "/opt/data", "/opt/logs"]

# http server
EXPOSE 9011
# swagger server
EXPOSE 9018
# internal server
EXPOSE 9019

# grpc server
EXPOSE 9020

CMD [./target/main, api, -release, -config=configs/prod.yaml, -http.addr=:9011, --grpc.addr=:9021, --internal.addr=:9019]
# CMD [./target/main, crons, -config=configs/crons.yaml]
# CMD [./target/main, swagger, -config=configs/swagger.yaml, -http.addr=:9018]
