FROM golang:1-alpine AS builder

ARG APP_Name
ARG APP_Version
ARG GO_ldflags
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>

LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=build

#SHELL ["/bin/bash", "-c"]

WORKDIR /apps

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    go env -w GOPROXY="https://goproxy.cn,direct"; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade

ADD ./main.go ./go.mod ./go.sum ./project.yaml ./
COPY ./internal ./internal
COPY ./migrations ./migrations
COPY ./pkg ./pkg
COPY ./proto ./proto
COPY ./bin ./bin
COPY ./deploy ./deploy

COPY ./cache.local ./cache.local

####
RUN mkdir -p target

RUN if [ -d ./cache.local/vendor ]; then \
    echo "==> Found cache.local/vendor"; \
    mv ./cache.local/vendor vendor; \
  fi

# in alpine, date doesn't parse %:z
# mkdir -p target && go build -o target/main -ldflags="-w -s ${GO_ldflags}" main.go

# https://docs.docker.com/reference/dockerfile/
# RUN --mount=type=cache,source=./cache.local/vendor,target=/apps/vendor \
#  go mod tidy && go build -ldflags="-w -s ${GO_ldflags}" -o target/main main.go

# note: -trimpath will remove -ldflags
RUN go build -ldflags="-w -s ${GO_ldflags}" -o target/main main.go

COPY ./build.yaml /apps/target/

####
RUN if [ -d ./bin/swagger-go/cache.local/vendor ]; then \
    echo "==> Found ./bin/swagger-go/cache.local/vendor"; \
    mv ./bin/swagger-go/cache.local/vendor bin/swagger-go/vendor; \
  fi

# note: -trimpath will remove -ldflags
RUN cd bin/swagger-go && \
  go build -ldflags="-w -s ${GO_ldflags}" -o ../../target/swagger main.go

####
FROM alpine:3

ARG APP_Name
ARG APP_Version
ARG region

MAINTAINER github.com/d2jvkpn <d2jvkpn@noreply.local>
LABEL app=${APP_Name}
LABEL version=${APP_Version}
LABEL stage=running
#SHELL ["/bin/bash", "-c"]

ENV APP_Name=${APP_Name}
ENV APP_Version=${APP_Version}
ENV TZ=${TZ:-Asia/Shanghai}

RUN if [ "$region" = "cn" ]; then \
    echo "==> region: $region"; \
    cp /etc/apk/repositories /etc/apk/repositories.bk; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
  fi

RUN apk --no-cache update && \
  apk --no-cache upgrade && \
  apk --no-cache add tzdata
  # curl gcompat

RUN mkdir -p /apps/target /apps/data /apps/logs
WORKDIR /apps

COPY --from=builder /apps/target/ /apps/target/
# COPY ./migrations ./migrations

VOLUME ["/apps/configs", "/apps/data", "/apps/logs"]

# http server
EXPOSE 9011
# swagger server
EXPOSE 9018
# internal server
EXPOSE 9019

# grpc server
EXPOSE 9020

CMD [./target/main, api, -release, -config=configs/prod.yaml, -http.addr=:9011, --grpc.addr=:9021, --internal.addr=:9019]
# CMD [./target/main, crons, -config=configs/crons.yaml]
# CMD [./target/main, swagger, -config=configs/swagger.yaml, -http.addr=:9018]
